# application.yml
# 🌐 Frank CardPayment Consumer Lambda Configuration
# -------------------------------------------
# Spring Boot Reactive microservice for AWS SNS/SQS payment flow.
# Consumes CardPayment events from SQS queue, tested on LocalStack.
#
# Author: Edoardo Sabatini
# Date: 15 October 2025
#
# PURPOSE:
# - Consumer service reads CardPayment events from SQS
# - Processes payments and triggers webhook to orchestrator
# - Minimal config, ready for LocalStack testing
#
# SERVICE:
# - CardPayment Consumer: :18083

server:
  port: 18083  # Consumer microservice port

spring:
  application:
    name: frank-aws-lambda-payment-card-consumer
  main:
    web-application-type: reactive  # Reactive Netty server

  cloud:
    aws:
      stack:
        name: localstack
        auto: false
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      endpoint:
        sns: http://localhost:4566  # LocalStack SNS endpoint
        sqs: http://localhost:4566  # LocalStack SQS endpoint

sqs:
  queue:
    cardpayment: cardpayment-queue  # SQS queue name for CardPayment

# Logging configuration
logging:
  level:
    root: INFO
    com.frankaws.lambda.payment.card.consumer: DEBUG

# Management endpoints for health checks and metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
