#!/bin/bash
# ================================================================
# setup_auto_env.sh
#
# Author: Edoardo Sabatini
# Date: 03 November 2025
# ================================================================
echo "🤖 Welcome to the FrankStack automatic environment setup script."
echo "Setting up .env.auto file..."
echo "------------------------------------------------"
MY_IP=$(hostname -I | awk '{print $2}')
echo "# Generated by FrankStack setup_auto_env.sh" > .env.auto
echo "# " >> .env.auto
echo "# Author: Edoardo Sabatini" >> .env.auto
echo "# Date: 03 November 2025" >> .env.auto
echo "# -----------------------------------------------" >> .env.auto
echo "HOST_IP=$MY_IP" >> .env.auto
echo "AWS_PAYMENT_SERVICE_URL=http://$MY_IP:18081/cardpayment/send" >> .env.auto
echo "ORCHESTRATOR_WEBHOOK_URL=http://$MY_IP:8081/frankcallback/card-payment-complete" >> .env.auto
echo "S3_ENDPOINT_URL=http://$MY_IP:4566" >> .env.auto
echo "LOCALSTACK_BASE=http://$MY_IP:4566/frank-aws-invoices/invoices" >> .env.auto
# ================================================================
# Copy .env.auto to frank-spring directory
# ================================================================
cp .env.auto frank-spring
cp .env.auto frank-aws/frank-aws-api-gateway
# ================================================================
echo "⚙️ Done! .env.auto created set to $MY_IP"
# ================================================================
# End of setup_auto_env.sh
# ================================================================
