# ================================================================
# docker-compose.aws.yml
# FrankStack - AWS Simulation (LocalStack + AWS Microservices)
# Structure: API Gateway + Service (PaymentCard) + Lambda (Producer/Consumer)
# Optimized: using .env file for configuration
#
# Author: Edoardo Sabatini
# Date: 29 October 2025
# ================================================================

version: '3.9'

#############################################################
#  NOTICE:
#  Using env_file: - .env to centralize container environment
#
#############################################################
#  NOTICE:
#  
# Explanation of the modification:
# DATA_DIR=/var/localstack/data: sets the folder where LocalStack will save its data.
# frank-aws_localstack_data:/var/localstack: mounts a dedicated Docker volume inside the container at /var/localstack.
# This way, LocalStack will no longer attempt to execute rm -rf "/tmp/localstack" and the dedicated volume
# is mounted in a directory that avoids conflicts on container startup.
#  
#############################################################

services:
  # ----------------------------
  # FrankStack LocalStack (AWS Mock)
  # ----------------------------
  frankstack-localstack:
    image: localstack/localstack:latest
    container_name: frankstack-localstack
    ports:
      - "${LOCALSTACK_PORT}:4566"
      - "${LOCALSTACK_LEGACY_PORT}:4571"
    env_file:
      - .env
    volumes:
      - frank-aws_localstack_data:/var/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frankstack-aws-net

  # ----------------------------
  # FrankStack AWS API Gateway
  # ----------------------------
  frankstack-aws-api-gateway:
    build:
      context: ./frank-aws-api-gateway
      dockerfile: Dockerfile
    container_name: frankstack-aws-api-gateway
    depends_on:
      - frankstack-localstack
    ports:
      - "${AWS_API_GATEWAY_PORT}:18081"
    env_file:
      - .env
    volumes:
      - maven-repo:/root/.m2
    networks:
      - frankstack-aws-net

# ------------------------------------------------------------------------------------
# AWS Service microservices
# ------------------------------------------------------------------------------------

  # ----------------------------
  # Payment Card Service
  # ----------------------------
  frankstack-aws-service-payment-card:
    build:
      context: ./frank-aws-service/frank-aws-service-payment-card
      dockerfile: Dockerfile
    container_name: frankstack-aws-service-payment-card
    depends_on:
      - frankstack-localstack
      - frankstack-aws-api-gateway
    env_file:
      - .env
    volumes:
      - maven-repo:/root/.m2
    networks:
      - frankstack-aws-net
      
# ------------------------------------------------------------------------------------
# Networks and Volumes
# ------------------------------------------------------------------------------------
networks:
  frankstack-aws-net:
    driver: bridge

volumes:
  maven-repo: {}
  frank-aws_localstack_data: {}
