# application.yml
# 
# frank-aws-service-payment-card
# 
# Author: Edoardo Sabatini
# Date: 23 October 2025
# ------------------------------------------------------
# Configuration file for the Payment Card Wrapper Service (Port 18082)
#
# PURPOSE:
# • Defines server-level properties for this Spring Boot WebFlux service.
# • Sets the HTTP server port explicitly to 18082 to avoid conflicts.
#
# NOTES:
# • This service listens for POST requests on /cardpayment/send.
# • Works with the LambdaInvokerService to invoke PaymentCard Lambda
#   running on LocalStack.
# • Keep this port consistent with the Docker container / test-wrapper.sh script.
#
server:
  port: 18082

aws:
  endpoint: ${AWS_ENDPOINT}
  lambda-name: ${AWS_LAMBDA_NAME}
  region: ${AWS_DEFAULT_REGION}
